# Generated by Django 3.2.8 on 2022-08-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('if_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=50, null=True)),
                ('emailid', models.CharField(max_length=50, null=True)),
                ('mobileNo', models.CharField(max_length=10, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('unread_msg', models.BooleanField(default=True)),
            ],
        ),
    ]
