# Generated by Django 3.2.8 on 2022-08-26 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifid', models.IntegerField(default=None, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=50, null=True)),
                ('year', models.CharField(choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], max_length=50, null=True)),
                ('grade', models.CharField(max_length=20, null=True)),
                ('attendance', models.FloatField(default=None, null=True)),
                ('salary', models.IntegerField(default=None, null=True)),
                ('training_att', models.FloatField(default=None, null=True)),
                ('training_salary', models.IntegerField(default=None, null=True)),
                ('bonus', models.IntegerField(default=None, null=True)),
                ('night_shift', models.FloatField(default=None, null=True)),
                ('rent', models.IntegerField(default=None, null=True)),
                ('other', models.FloatField(default=None, null=True)),
                ('total_salary', models.IntegerField(default=None, null=True)),
                ('total_other_income', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SalaryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=50, null=True, verbose_name='Enter Year')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=50, null=True, verbose_name='Enter Month')),
                ('file', models.FileField(upload_to='salary_data')),
            ],
        ),
        migrations.CreateModel(
            name='salaryMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=50, null=True)),
                ('year', models.CharField(choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='specialIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HRA', models.FloatField(default=None, null=True)),
                ('invest_profit', models.FloatField(default=None, null=True)),
                ('Rsg_settlement', models.FloatField(default=None, null=True)),
                ('minimum_wage', models.FloatField(default=None, null=True)),
                ('survey_scheme', models.FloatField(default=None, null=True)),
                ('from_last_month', models.FloatField(default=None, null=True)),
                ('festival_bonus', models.FloatField(default=None, null=True)),
                ('savings', models.FloatField(default=None, null=True)),
                ('total', models.FloatField(default=None, null=True)),
                ('basicSalary', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='salary.salarydetails')),
            ],
        ),
        migrations.CreateModel(
            name='GrandTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(default=None, null=True)),
                ('basicSalary', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='salary.salarydetails')),
            ],
        ),
        migrations.CreateModel(
            name='Deductions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_next_month', models.FloatField(default=None, null=True)),
                ('other', models.FloatField(default=None, null=True)),
                ('total', models.FloatField(default=None, null=True)),
                ('basicSalary', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='salary.salarydetails')),
            ],
        ),
    ]
