# Generated by Django 3.2.8 on 2022-08-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xlfile', models.FileField(upload_to='credfiles')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeMobile',
            fields=[
                ('ifid', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('mobile', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
